### ISSUE TITLE
Error when compile on Windows

### ISSUE THREAD

**Issue by Yxelahh** [NeoTech-Software/Android-Root-Coverage-Plugin#64]
## Context 

- Plugins version 1.5.2
- Windows 11 
- Android studio Chipmunks
- Gradle version 7.2.1
- Project multi module

## What's the problem? 

Hi! 😄 

Great job for this plugin!
I have an error when I try to sync Gradle.
My IDE can't compile and return this error, it works in my github actions and works on MAC but not on my Windows machine. If i remove your plugins, it's works. 

Can you help me? 
Thanks in advance

## Error logs

`Illegal char <:> at index 66: C:\Users\MyProjectPath\:MyModuleName
	at org.gradle.api.internal.file.AbstractBaseDirFileResolver.resolveAsRelativePath(AbstractBaseDirFileResolver.java:30)
	at org.gradle.api.internal.file.DefaultFileOperations.relativePath(DefaultFileOperations.java:224)
	at org.gradle.api.internal.project.DefaultProject.relativePath(DefaultProject.java:993)
	at org.neotech.plugin.rootcoverage.RootCoveragePlugin.addSubProjectVariant(RootCoveragePlugin.kt:168)
	at org.neotech.plugin.rootcoverage.RootCoveragePlugin.access$addSubProjectVariant(RootCoveragePlugin.kt:25)
	at org.neotech.plugin.rootcoverage.RootCoveragePlugin$addSubProjectInternal$2.invoke(RootCoveragePlugin.kt:159)
	at org.neotech.plugin.rootcoverage.RootCoveragePlugin$addSubProjectInternal$2.invoke(RootCoveragePlugin.kt:156)
`

## Possible solution

Maybe at the line 168 of RootCoveragePlugin.kt, you remove suffixe ":" too late.
**Replace** 
`val path = project.relativePath(subProject.path).removeSuffix(":")`
**by**
`val path = project.relativePath(subProject.path.removeSuffix(":"))`

**Comment by Rolf-Smit** [comment]
@Yxelahh Thanks for reporting this bug, a fix should be available in version 1.5.3.

Let me know if you have any problems!

**Comment by Yxelahh** [comment]
Thanks for your fast fix. 
It's works well! ;)
